In [3]:
import numpy as np
import pandas as pd

In [20]:
data = {
    "Numeric1" : [1, np.nan, 3, 4],
    "Numeric2" : [5, 6, np.nan, 8.2],
    "Category" : ['dog', np.nan, 'cat', 'dog']
    }

df = pd.DataFrame(data)
df

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN
2       3.0       NaN      cat
3       4.0       8.2      dog

In [21]:
data = {
    '나이' : [22,35,14,55,42]
}

df = pd.DataFrame(data)

def categorize(data):
    if 0<data<-10:
        return "10대"
    elif 10<data<=20:
        return "20대"
    elif 20<data<=30:
        return "30대"
    else:
        return "30대이상"

df["검사나이"]= df["나이"].apply(categorize)
df

   나이   검사나이
0  22    30대
1  35  30대이상
2  14    20대
3  55  30대이상
4  42  30대이상

In [145]:
data = {
    "Numeric1" : [1, np.nan, 3, 4],
    "Numeric2" : [5, 6, np.nan, 8.2],
    "Category" : ['dog', np.nan, 'cat', 'dogg']
    }

df = pd.DataFrame(data)

filter_df = df[df['Category'] =='dog']

filter_df_contains = df[df['Category'].str.contains('do', na=False)]

filter_df_contains

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
3       4.0       8.2     dogg

In [45]:
df = pd.DataFrame({
    'variable':['value1-value2-value3', 'value4-value5','value6']
})

split_df=df['variable'].str.split('-', expand=True)

split_df.columns=['var1','var2','var3']
split_df

     var1    var2    var3
0  value1  value2  value3
1  value4  value5    None
2  value6    None    None

In [5]:
df = pd.DataFrame({
    'variable':['value1-value2-value3', 'value4-value5','value6']
})

df['variable'] = df['variable'].str[0:5]
df['variable'] = df['variable'].str[0:5]+df['variable'].str[6:12]

df

  variable
0    value
1    value
2    value

In [52]:
df['var1']=df['var1'].astype(str)
df['var2']=df['var2'].astype(str)
df['var3']=df['var3'].astype(str)

df['combined']=df['var1']+'-'+df['var2']+'-'+df['var3']

KeyError: 'var1'

In [53]:
#오른쪽 , 다 지워짐
text = "apple,"
result = text.rstrip(",")
print(result)
# , 다 지워짐
text="banana,,"
result=text.rstrip(",")
print(result)
#왼쪽 , 다 지워짐
text=",orange,pear"
result=text.lstrip(",")
print(result)

apple
banana
orange,pear

In [79]:
df = pd.DataFrame({
    "문항1":['1','2'," ",'2'],
    "문항2":[" ",'2','3'," "]
})
df
df[" 문항 "]=df["문항1"].fillna(" ")+","+df["문항2"].fillna(" ")
df[" 문항 "]=df["문항1"].str.rstrip(", ")
df[" 문항 "]=df["문항1"].str.lstrip(",")
df=df.drop(columns=["문항1", "문항2"])
print(df)

  문항
0   1
1   2
2
3   2

In [92]:
df = pd.DataFrame({
    "문항1":['1','2'," ",'2'],
    "문항2":[" ",'2','3'," "],
    "문항3":[" ",'1','2',""]
})

cols=["문항1","문항2","문항3"]
df[cols]=df[cols].replace(r'^\s*$','무응답',regex=True)

df["문항"]=df["문항1"]+","+df["문항2"]+","+df["문항3"]

print(df)

   문항1  문항2  문항3         문항
0    1  무응답  무응답  1,무응답,무응답
1    2    2    1      2,2,1
2  무응답    3    2    무응답,3,2
3    2  무응답  무응답  2,무응답,무응답

In [96]:
df = pd.DataFrame({
    'variable':['value1-value2-value3', 'value3-value1-value5','vvdfvalue165656']
})
df["new_variable"]=df['variable'].str.replace(r'value1.*','value1',regex=True)

print(df["new_variable"])

0           value1
1    value3-value1
2       vvdfvalue1
Name: new_variable, dtype: object

In [98]:
df = pd.DataFrame({
    'variable':['value1-value2-value3', 'value3-value1-value5','vvdfvalue165656']
})

df["new_variable"]=df['variable'].str.extract(r'(value1)')
print(df["new_variable"])

0    value1
1    value1
2    value1
Name: new_variable, dtype: object

In [100]:
df = pd.DataFrame({
    'variable':['value1-value2-value3', 'value3-value1-value5','vvdfvalue165656']
})

df["new_variable"]=df['variable'].str.extract(r'(value2)')
print(df["new_variable"])

0    value2
1       NaN
2       NaN
Name: new_variable, dtype: object

In [4]:
import pandas as pd
data={'date':['202103151345','20210315 1345', '0715', '07-15', '20210315', '1']}
df=pd.DataFrame(data)

#2번째 데이터만 연,월,날짜,시,분 으로 나옴 
#df['date']=pd.to_datetime(df['date'],format='%Y%m%d %H%M', errors='coerce')

#.dt.time 으로 시간데이터 
df['date']=pd.to_datetime(df['date'],format='%H%M', errors='coerce').dt.time

#df['date']=pd.to_datetime(df['date'],format='%Y%m%d', errors='coerce')

#.dt.time 을 안쓰면 앞에 랜덤한 연월도 나옴
#df['date']=pd.to_datetime(df['date'],format='%H-%M', errors='coerce')

df

       date
0       NaT
1       NaT
2  07:15:00
3       NaT
4       NaT
5       NaT

In [142]:
data = {'hour':['1','2','12','22','11']}
df=pd.DataFrame(data)

df['hour']=df['hour'].str.rjust(4,fillchar='0')

#df['hour']=df['hour'].str.ljust(4,fillchar='0')
df['hour'] = pd.to_datetime(df['hour'],format='%H%M', errors='coerce').dt.time
df

       hour
0  00:01:00
1  00:02:00
2  00:12:00
3  00:22:00
4  00:11:00

In [144]:
df.to_csv('new_program.csv', index=False)

df.to_csv('new_program.csv', index=False, encoding='cp949')